data:extend({
	{
		type = "module",
		name = "quality-acceleration-module-1",
		icon = "__grogs-quality-hell__/graphics/icons/quality-acceleration-1.png",
		subgroup = "module",
		category = "quality-acceleration",
		tier = 1,
		stack_size = 50,
		weight = 10 * kg,
		effect = { speed = -0.05 },
	},
	{
		type = "module",
		name = "quality-acceleration-module-2",
		icon = "__grogs-quality-hell__/graphics/icons/quality-acceleration-2.png",
		subgroup = "module",
		category = "quality-acceleration",
		tier = 2,
		stack_size = 50,
		weight = 10 * kg,
		effect = { speed = -0.05 },
	},
	{
		type = "module",
		name = "quality-acceleration-module-3",
		icon = "__grogs-quality-hell__/graphics/icons/quality-acceleration-3.png",
		subgroup = "module",
		category = "quality-acceleration",
		tier = 3,
		stack_size = 50,
		weight = 10 * kg,
		effect = { speed = -0.05 },
	},
})