data:extend({
	{
		type = "module",
		name = "hidden-quality-module-0",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-0.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 1,
		effect = { quality=0.01 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-1",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-1.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 2,
		effect = { quality=0.02 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-2",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-2.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 3,
		effect = { quality=0.04 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-3",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-3.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 4,
		effect = { quality=0.08 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-4",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-4.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 5,
		effect = { quality=0.16 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-5",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-5.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 6,
		effect = { quality=0.32 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-6",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-6.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 7,
		effect = { quality=0.64 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-7",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1-7.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 2,
		effect = { quality=1.28 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-8",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 9,
		effect = { quality=2.56 },
		hidden = true,
	},
	{
		type = "item",
		name = "hidden-quality-module-9",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 10,
		effect = { quality=5.12 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-10",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 11,
		effect = { quality=10.24 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-11",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 12,
		effect = { quality=20.48 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-12",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 13,
		effect = { quality=40.96 },
		hidden = true,
	},
	{
		type = "module",
		name = "hidden-quality-module-13",
		icon = "__grogs-quality-hell__/graphics/icons/hidden-module-1.png",
		subgroup = "module",
		category = "hidden-quality",
		stack_size = 1,
		tier = 14,
		effect = { quality=81.92 },
		hidden = true,
	}
})